#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/prezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/dotfiles/prezto/init.zsh"
fi

SAVED_ZSHRC="$HOME/dotfiles/zshrc"
source $SAVED_ZSHRC

LOCAL_ZSHRC="$HOME/.local_zshrc"
if [ -f $LOCAL_ZSHRC ]; then
    source $LOCAL_ZSHRC
fi
